require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '12.4'

target 'demo' do
  config = use_native_modules!
  use_react_native!(:path => config[:reactNativePath])


  target 'demoTests' do
    inherit! :complete
    # Pods for testing
  end

end

# Patch for XCode 15: https://github.com/facebook/react-native/issues/37748
# Shouldn't be necessary when we migrate to React Native > 0.72
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)', '_LIBCPP_ENABLE_CXX17_REMOVED_UNARY_BINARY_FUNCTION']
    end
  end
end
