default_platform(:ios)

before_all do
  setup_circle_ci

  %w[FASTLANE_APPSTORE_CONNECT_KEY_ID FASTLANE_APPSTORE_CONNECT_KEY_ISSUER_ID
    FASTLANE_APPSTORE_CONNECT_KEY].each do |envvar|
    UI.user_error! "Missing environment variable #{envvar}" unless ENV[envvar]
  end

  app_store_connect_api_key(
    key_id: ENV['FASTLANE_APPSTORE_CONNECT_KEY_ID'],
    issuer_id: ENV['FASTLANE_APPSTORE_CONNECT_KEY_ISSUER_ID'],
    key_content: ENV['FASTLANE_APPSTORE_CONNECT_KEY'],
    is_key_content_base64: true
  )
end

platform :ios do
  lane :install_provisioning_profiles do
    match
  end

  desc "Push a new beta build to TestFlight"
  lane :beta do |options|
    ipa = options[:ipa]
    UI.user_error! "Missing parameter ipa" unless ipa

    upload_to_testflight(
      ipa: ipa,
      distribute_external: true,
      groups: ["External"],
      changelog: "Refer to the changelog for the list of changes: https://geniusscansdk.com/docs/changelog/",
      reject_build_waiting_for_review: true
    )
  end
end
