platform :ios, '11.0'

target 'GSSDKCustomDemo' do

  pod 'GSSDK/Core', :podspec => 'https://s3.amazonaws.com/tgl.geniusscan.sdk/GSSDK-.podspec'
  pod 'GSSDK/OCR', :podspec => 'https://s3.amazonaws.com/tgl.geniusscan.sdk/GSSDK-.podspec'

end
