using GeniusScanSDK.ScanFlow;

namespace SimpleDemo;

public partial class MainPage : ContentPage
{

    private readonly ScanFlowService scanFlowService = new();

	public MainPage()
	{
		InitializeComponent();

        // This code shows how to initialize the SDK with a license key.
        // Without a license key, the SDK runs for 60 seconds and then the app needs to be restarted.
        //
        // scanFlowService.SetLicenseKey("<Your license key>");
    }

    async void StartDocumentScanning(object sender, EventArgs args)
    {
        try
        {
            var configuration = new Dictionary<string, object>
            {
                ["source"] = "camera",
                ["ocrConfiguration"] = new Dictionary<string, object>
                {
                    ["languages"] = new string[] { "en-US" },
                }
            };

            var result = await scanFlowService.ScanDocument(configuration);

            // Retrieve the document generated by the ScanFlow
            var documentUri = (string)result["multiPageDocumentUrl"];

            // Or generate your custom document from scans
            var customDocumentUri = GenerateCustomDocument(result);
            Console.WriteLine(customDocumentUri);

            await Launcher.OpenAsync(new OpenFileRequest
            {
                File = new ReadOnlyFile(new Uri(customDocumentUri).AbsolutePath)
            });
        }
        catch (Exception e)
        {
            Console.WriteLine(e.ToString());
            await DisplayAlert("Alert", "Error: " + e.Message, "OK");
        }
    }

    async void StartBarcodeScanning(object sender, EventArgs args)
    {
        try
        {
            var configuration = new Dictionary<string, object>
            {
                ["isBatchModeEnabled"] = true,
                ["supportedCodeTypes"] = new string[] { "qr", "code128", "ean13" }
            };

            var result = await scanFlowService.ScanBarcodes(configuration);

            var codesText = ((IEnumerable<object>)result["barcodes"])
                .OfType<Dictionary<string, object>>()
                .Select(code => $"{code["type"]}: {code["value"]}");

            await DisplayAlert("Barcodes", string.Join(Environment.NewLine, codesText), "OK");
        }
        catch (Exception e)
        {
            Console.WriteLine(e.ToString());
            await DisplayAlert("Alert", "Error: " + e.Message, "OK");
        }
    }

    private string GenerateCustomDocument(Dictionary<string, object> scanFlowResult)
    {
        var pages = ((ICollection<object>)scanFlowResult["scans"]).Select
        (scan =>
            new Dictionary<string, object>
            {
                ["imageUrl"] = ((Dictionary<string, object>)scan)["enhancedUrl"]
            }
        );
        var document = new Dictionary<string, object>
        {
            ["pages"] = pages
        };
        var documentUrl = "file://" + FileSystem.Current.AppDataDirectory + "/document.pdf";
        var pdfConfiguration = new Dictionary<string, object>
        {
            ["outputFileUrl"] = documentUrl
        };
        scanFlowService.GenerateDocument(document, pdfConfiguration);
        return documentUrl;
    }
}
