// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from sdk.djinni

#import <Foundation/Foundation.h>


@protocol GSKPDFImageProcessor

/**
 * Process the image and return a file path to the
 * updated image. The PDF processor will delete this temporary
 * image afterwards (only if it's different from @param input_file_path)
 * @return NULL if there is an error
 *
 */
- (nullable NSString *)process:(nonnull NSString *)inputFilePath;

@end
