// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from sdk.djinni

#import "GSKPDFPage.h"
#import <Foundation/Foundation.h>

@interface GSKPDFDocument : NSObject
- (nonnull instancetype)initWithTitle:(nullable NSString *)title
                             password:(nullable NSString *)password
                             keywords:(nullable NSString *)keywords
                                pages:(nonnull NSArray<GSKPDFPage *> *)pages;
+ (nonnull instancetype)PDFDocumentWithTitle:(nullable NSString *)title
                                    password:(nullable NSString *)password
                                    keywords:(nullable NSString *)keywords
                                       pages:(nonnull NSArray<GSKPDFPage *> *)pages;

@property (nonatomic, readonly, nullable) NSString * title;

@property (nonatomic, readonly, nullable) NSString * password;

@property (nonatomic, readonly, nullable) NSString * keywords;

@property (nonatomic, readonly, nonnull) NSArray<GSKPDFPage *> * pages;

@end
