// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from sdk.djinni

#import <Foundation/Foundation.h>

@interface GSKPDFSize : NSObject
- (nonnull instancetype)initWithWidth:(double)width
                               height:(double)height;
+ (nonnull instancetype)PDFSizeWithWidth:(double)width
                                  height:(double)height;

@property (nonatomic, readonly) double width;

@property (nonatomic, readonly) double height;

@end
