// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from sdk.djinni

#import "GSKPDFSize.h"
#import <Foundation/Foundation.h>

@interface GSKPDFPage : NSObject
- (nonnull instancetype)initWithFilePath:(nonnull NSString *)filePath
                              inchesSize:(nonnull GSKPDFSize *)inchesSize;
+ (nonnull instancetype)PDFPageWithFilePath:(nonnull NSString *)filePath
                                 inchesSize:(nonnull GSKPDFSize *)inchesSize;

@property (nonatomic, readonly, nonnull) NSString * filePath;

@property (nonatomic, readonly, nonnull) GSKPDFSize * inchesSize;

@end
