// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from sdk.djinni

#import <Foundation/Foundation.h>

typedef NS_ENUM(NSInteger, GSKPDFGeneratorError)
{
    GSKPDFGeneratorErrorPDFGeneratorErrorCodeSuccess,
    GSKPDFGeneratorErrorPDFGeneratorErrorCodeInternal,
    GSKPDFGeneratorErrorPDFGeneratorErrorCodeFileNotFound,
    GSKPDFGeneratorErrorPDFGeneratorErrorCodeInvalidPassword,
    GSKPDFGeneratorErrorPDFGeneratorErrorCodeInvalidPageSize,
    GSKPDFGeneratorErrorPDFGeneratorErrorCodeProcessorError,
};
